# Sber/fullstack/docker-compose.yml

services:

  backend:
    build:
      context: ./backend
      args:
        - REQUIREMENTS_FILE=requirements-dev.txt
    ports:
      - "8000:8000"
    volumes:
      - ./backend/passports:/app/passports
      - ./backend/uploads:/app/uploads
    environment:
      # Передаем секреты как переменные окружения, а не храним в коде
      - DB_USER=postgres
      - DB_PASS=mastdmastd
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=sber_project
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/my-react-app
      args:
        - VITE_API_BASE_URL=http://77.239.125.100:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mastdmastd
      - POSTGRES_DB=sber_project
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: # Создаем именованный том для данных БД